### ISSUE TITLE
Wrong Controller Code referenced in scripts

### ISSUE THREAD

**Issue by snowowl78** [SymfonyCasts/symfony6#24]
Following the scripts I ran into a wrong code reference in `controllers-services.md` of the SymfonyCasts fundamentals tutorial
```
## Binding Action Arguments

And, the action methods really *do* work *just* like the constructors when it comes
to autowiring. For example, add a `bool $isDebug` argument to the `browse()` action...
then `dump($isDebug)` below:

[[[ code('d77a8d195f') ]]]
```
This reference links to a snippet from `MixRepository` and not `VinylController` as expectable by the scripts text.

I was not able to find the right reference this link needs to point to.

**Comment by MolloKhan** [comment]
Hey @snowowl78 thanks for reporting it. You're right, I just replaced the wrong code block

Cheers!
